### ISSUE TITLE
Lazy Minted Items Don't Show Correct Creator on OpenSea

### ISSUE THREAD

**Issue by mynamebrody** [rarible/protocol#1]
I've got an issue where a lazy minted NFT from Rarible ended up with a null creator on OpenSea after it was purchased and actually minted. 

The expected behavior would be for it to show up in the OpenSea account for that user as the creator. 

Rarible:
https://rarible.com/token/0xb66a603f4cfe17e3d27b87a8bfcad319856518b8:95765504400613452714159102908317164126071985149556277575149904226646891692033?tab=bids

OpenSea:
https://opensea.io/assets/0xb66a603f4cfe17e3d27b87a8bfcad319856518b8/95765504400613452714159102908317164126071985149556277575149904226646891692033

Etherscan:
https://etherscan.io/tx/0x3bdf52280d9c7dffec9cad23d6228a89583dff21db26ad50ee7cf39b5dc219e1

---

I just looked back at one of our first posts and it even got assigned to a totally random creator in OpenSea. https://discord.com/channels/846402262443491328/846458744560549968/860987953344807012

So overall, this happens randomly if it's this random creator or an empty creator.

**Comment by mynamebrody** [comment]
Curious if there was an update on this? @evgenynacu

**Comment by arsena21** [comment]
from what I was told, they are not indexed on opensea

**Comment by arsena21** [comment]
Is this after it gets minted?

**Comment by mynamebrody** [comment]
Correct. This is for when the item is actually minted that was once lazy
minted.

**Comment by evgenynacu** [comment]
We need to do a workaround with emitting transfer event from 0 address to creator and then from creator to buyer.
Can you make a PR to solve this? @mynamebrody 

I can help with links to the code needed to be fixed

**Comment by mattreallycodes** [comment]
This is due to the mintAndTransfer function transferring from the 0 address instead of the creator. Fix needs to address minting and transferring to creator then buyer as mentioned above.

**Comment by evgenynacu** [comment]
@mattreallycodes this doesn't help actually. deployed and tested this in rinkeby, contacted to OpenSea about it

**Comment by evgenynacu** [comment]
I believe this is solved right now
