### ISSUE TITLE
Metadata not refreshed properly

### ISSUE THREAD

**Issue by bruck93** [rarible/protocol#118]
I've added other things to this Issue: https://github.com/rarible/protocol-issues/issues/93

But I'll open a new one here.
OctoHeadz collection ( https://opensea.io/collection/octohedz ) didn't have the metadata refreshed properly.

**Comment by sanufriev** [comment]
@bruck93 could you point what is it wrong with collection? I check some items and it seems all ok

**Comment by evgenynacu** [comment]
@bruck93 thanks for the information. Will check.
Sorry for late reply

**Comment by eduardstal** [comment]
Beeple collection seems indexed now. Closing.
