### ISSUE TITLE
Items removed from Rarible.com are showing up in Indexer

### ISSUE THREAD

**Issue by mynamebrody** [rarible/protocol#120]
Items that have been removed from Rarible.com are still being pulled by the indexer APIs.
(ie. [Rarible](https://rarible.com/token/0x3deb701b7f157f95f72fb1fcead7a3248a50549e:77648542208174037529171678517440624449737224618930764378799162790255813197844?tab=owners) | [cocoNFT page](https://coconft.com/p/MHgzZGViNzAxYjdmMTU3Zjk1ZjcyZmIxZmNlYWQ3YTMyNDhhNTA1NDllOjc3NjQ4NTQyMjA4MTc0MDM3NTI5MTcxNjc4NTE3NDQwNjI0NDQ5NzM3MjI0NjE4OTMwNzY0Mzc4Nzk5MTYyNzkwMjU1ODEzMTk3ODQ0))

You can see the cocoNFT page is pulling all of this info in from the protocol. It's a copyminter. I believe items like these should not appear in the indexer as the majority of them are either illegal activity and/or copyrighted material. If they are all being reported back to Rarible and removed, why make every user of the protocol redo that work and remove it from their platform?  

Or a compromise would be some sort of flag on the API response such as `hidden: true` that way you can signify it's hidden on Rarible.com or something. Even an endpoint parameter where you can say you don't want **any** hidden items to be return in the response would be amazing. It'd be up to the consumer of the API to decide if they want to have Rarible.com controlling this field. If they don't they don't need to filter on that hidden flag and can just consume everything and have their own policies of hiding content.

---

Update to Original Post: the "cocoNFT Link" will no longer work. We built in our own hiding capability, but we have to hide individual posts as they crop up.

**Comment by bobwith2bees** [comment]
It would be nice to have a pointer to a ticket/case with status link.  

A simple boolean flag doesn't help someone get their token re-listed in case of an accidental ban etc...

**Comment by artsyassets** [comment]
This would be useful to me. I did not know that the old version of the contract (one made through the Rarible UI) is different and does not support lazy minting. I lazy minted several items through the API and then found out that, since the underlying contract doesn't support it, all of the buying, minting, burning, etc. functions are broken for those items. Buyers go to buy, the new pieces show up in my collection, but the buyers get an error. Now these pieces are just sitting there stuck in my collection confusing buyers. Hiding them would be wonderful.

**Comment by eduardstal** [comment]
Hey Brody. 

We haven't found a fix for this yet using the protocol. I believe until we're ready to decentralise this feature the issue should be considered a wont-fix. 

On the other side, the API from Rarible.com could be used to find out if an item is banned/blacklisted. (See issue: https://github.com/rarible/protocol/issues/152) 

In case on any updates on this the issue will be reopened.
