### ISSUE TITLE
External royalties not updating in API

### ISSUE THREAD

**Issue by ptrwtts** [rarible/protocol#133]
I followed the instructions here to add Royalties to an external collection:

https://docs.rarible.org/asset/royalties-on-a-external-collection

Here is the transaction:

https://etherscan.io/tx/0xb5f625595fed64d629818401b61342d1f0443867fa866fe588d442f36804f834

But it has been days, and it is not reflected in the API:

https://ethereum-api.rarible.org/v0.1/nft/items/0x819327e005a3ed85f7b634e195b8f25d4a2a45f8:35739319466029867409935893104794648465119721019613204601875682368845852747852?includeMeta=true

Did I do something wrong, or is there a bug?

**Comment by evgenynacu** [comment]
quick update: this is already working on the protocol side: https://ethereum-api.rarible.org/v0.1/nft/items/0x819327e005a3ed85f7b634e195b8f25d4a2a45f8:35739319466029867409935893104794648465119721019613204601875682368845852747852/royalty

rarible.com should use this api to fetch royalties when Item is shown.

royalties from Item domain model can't be used to query this data, it's hard to update it

**Comment by ptrwtts** [comment]
Thanks
