### ISSUE TITLE
API's getSellOrdersByMaker returns sell order for NFT that account no longer owns

### ISSUE THREAD

**Issue by evgenynacu** [rarible/protocol#134]
### Discussed in https://github.com/rarible/protocol-issues/discussions/115

<div type='discussions-op-text'>

<sup>Originally posted by **azflin** October  4, 2021</sup>
See this query: https://ethereum-api.rarible.org/v0.1/order/orders/sell/byMaker?maker=0x785ba9ba76f9c2f1c07aeb27c64683dfa9281cf3&size=1000. It contains an order of hash "0x0470a33dbfb5dbd39b90d3fa5b945d0421ccd744bfe972f51ee6f8382485fd56", which is a sell order for an NFT that this account 0x785ba9ba76f9c2f1c07aeb27c64683dfa9281cf3 no longer owns. Please advise.</div>

**Comment by evgenynacu** [comment]
@azflin pls follow here for the status updates

**Comment by eduardstal** [comment]
This looks fixed now as makeStock is 0.
