### ISSUE TITLE
Semantic errors in API

### ISSUE THREAD

**Issue by unchase** [rarible/protocol#137]
I uploaded the yaml spec to https://editor.swagger.io/, there are two errors:

![image](https://user-images.githubusercontent.com/29679226/137366314-9e670a2c-c02a-4cd4-8d4a-99239b531f79.png)

Can you check it?

**Comment by unchase** [comment]
Hi, @mazinden
Did you manage to fix it?

I see another error:

![image](https://user-images.githubusercontent.com/29679226/139524174-c80192ba-af1c-4cff-b183-61fe759c41a2.png)

**Comment by mazinden** [comment]
Hi, @unchase!
Previous errors are already fixed. And will be arrived in the ethereum-indexer 1.17 release.
About the last error - it is from union protocol API. And I can't reproduce this. Maybe we have already fixed this)

**Comment by unchase** [comment]
Hi, @mazinden 
Now everything is ok:

![image](https://user-images.githubusercontent.com/29679226/140716586-c38f4982-d969-432a-88a4-fdfa0e9c9041.png)
