### ISSUE TITLE
Indexer not loading this collection

### ISSUE THREAD

**Issue by nfttrader** [rarible/protocol#138]
Hi, the indexer seems not be loading this full collection properly. https://opensea.io/collection/fewocious-x-rtfkt
Please update as some of our users are waiting on this. Thank you very much

**Comment by nfttrader** [comment]
Hi again, sorry more users are requesting support for this collection FEWOCiOUS x RTFKT in the indexer. Please update asap, thank you.

**Comment by nfttrader** [comment]
Hi any update on this? Please we are losing users as they cannot trade these nfts because the "drip" collection is not listed on the indexer. Thank you.

**Comment by sanufriev** [comment]
@nfttrader hello, why do you think that this collection is not present in indexer?
1. collection
https://ethereum-api.rarible.org/v0.1/nft/collections/0x2250d7c238392f4b575bb26c672afe45f0adcb75

2. items
https://ethereum-api.rarible.org/v0.1/nft/items/byCollection?collection=0x2250d7c238392f4b575bb26c672afe45f0adcb75&size=1000&continuation=

What exactly are your uses complaining about ?

**Comment by eduardstal** [comment]
After a private discussion with @nfttrader we both agreed that this issue should be closed as the issue was fixed.
