### ISSUE TITLE
500 service internal error on ethereum-api-staging.rarible.org/v0.1/nft/mints

### ISSUE THREAD

**Issue by bobwith2bees** [rarible/protocol#140]
Post to the rinkby lazy mint fails with 500 internal server error

Body of Post to ethereum-api-staging.rarible.org/v0.1/nft/mints:
`
{"@type":"ERC721","contract":"0xf565108F208136B1AffD55d19A6236b6b6b9786D","tokenURI":"/ipfs/QmQMid5Nbaqi8M4FNho2aBPDyixU4JozX2Rx2LoijHWheg","uri":"/ipfs/QmQMid5Nbaqi8M4FNho2aBPDyixU4JozX2Rx2LoijHWheg","tokenId":"51853873187524799243313032258623492611584136611923237689466576623960428904451","creators":[{"account":"0x72A4408DA42DE870499c1841D0e4a49f864e34ba","value":10000}],"royalties":[{"account":"0x72A4408DA42DE870499c1841D0e4a49f864e34ba","value":20000}],"signatures":["0xed332bffa0de8d64a9ea456b2af82dfb81b683adc2b1f11c5b90fb53004f6edd10ac667f2bb7aeab55b70ade99b1cd253094958932d487cacd6a61b461d04ce92c"]}
`

---
Initialized Rarible on rinkeby (chain ID: 4) with basePath https://ethereum-api-staging.rarible.org/
Collection Address: 0xf565108F208136B1AffD55d19A6236b6b6b9786D - https://rinkeby.rarible.com/collection/0xf565108F208136B1AffD55d19A6236b6b6b9786D
Minter Wallet address: 0x72A4408DA42DE870499c1841D0e4a49f864e34ba

Suspects 
- I still have a bad signature?  
- Or the collection from the token factory has not properly been deployed?

**Comment by evgenynacu** [comment]
@bobwith2bees thank you for this information
Reproduced, will fix soon

**Comment by evgenynacu** [comment]
@bobwith2bees how did you get this signature?
It's v is 44
That's the problem

We will fix error message and http status (should be 400 here)

**Comment by bobwith2bees** [comment]
OK - quick follow up on signature if appropriate.   More for documentation -   

The signing library I am calling is a port of the eth_sig_utils, and it has an optional chainId parameter.   Should all signatures be signed without the chainId specified?   I.e. there is no need for replay protection for such a signature?   ( https://eips.ethereum.org/EIPS/eip-155 )

**Comment by eduardstal** [comment]
Hey @bobwith2bees, I think this might have been fixed. Can you check on your end so we can close this issue?

**Comment by bobwith2bees** [comment]
Tested on rinkeby https://ethereum-api-staging.rarible.org/v0.1/nft/mints

* The original post above still returns a 500 service error.  
* Adjusting the last two bytes of the signature from 2c -> 1c returns a 400 - Invalid signatures for creators [0x72a4408da42de870499c1841d0e4a49f864e34ba]

**Comment by evgenynacu** [comment]
@bobwith2bees here chainId is not used. Chain id in eip-712 used in calculated hash.
Regarding 400 error when you try to post the message to API:

That's pretty difficult to debug: you should check all data types for correctness. 
How do you prepare signature for EIP-712 message? Do you use any library? What types you use to do this?

**Comment by evgenynacu** [comment]
Also, if you use js/ts, pls, use SDK to do all of this.

**Comment by bobwith2bees** [comment]
Testing on https://ethereum-api-staging.rarible.org/v0.1/nft/mints now returns a 400

```
{
    "code": "VALIDATION",
    "message": "Invalid structure of signature [0xed332bffa0de8d64a9ea456b2af82dfb81b683adc2b1f11c5b90fb53004f6edd10ac667f2bb7aeab55b70ade99b1cd253094958932d487cacd6a61b461d04ce92c] - Value of 'v' is not recognised: 44",
    "status": 400
}
```

**Comment by subsub-wp** [comment]
> https://ethereum-api-staging.rarible.org/v0.1/nft/mints 에서 테스트하면 이제 400이 반환 됩니다.
> 
> ```
> {
>     "code": "VALIDATION",
>     "message": "Invalid structure of signature [0xed332bffa0de8d64a9ea456b2af82dfb81b683adc2b1f11c5b90fb53004f6edd10ac667f2bb7aeab55b70ade99b1cd253094958932d487cacd6a61b461d04ce92c] - Value of 'v' is not recognised: 44",
>     "status": 400
> }
> ```
I have the same problem. how did you ever solve it

**Comment by bobwith2bees** [comment]
@subsub-wp  - My notes: 
* When performing a signature request use chainId 1 with the eth_sig_tools API.
* The NFT target chainId is captured within the SignedTypedData message, and can be different.
* The validation contract must correspond to the chainId within the SignedTypedData message.  (Each chan has a unique contract.)

**Comment by adamnguyenqa** [comment]
@bobwith2bees can you explain for me more detail cause i have same problem im using web3.eth.personal.sign to get signature when connect wallet but still get "Invalid signatures for creators [...(This is my contract im connected)]"

**Comment by bobwith2bees** [comment]
@adamnguyenqa You need to request a signedTypedData request, not a personal sign using your eth tools.   TypedData requests provide the receiving wallet some guidance to what is being signed (in terms of data)  and how to format it for the end user.  

There are other cases with the Rarible API when you just need a personal signature (say when you want to delete a lazy minted item that has not been minted yet...   There is another github issue that shows how to do that ;-)
