### ISSUE TITLE
NFT collection issue

### ISSUE THREAD

**Issue by nfttrader** [rarible/protocol#144]
Some users are having issues with the Voxies collection of NFTs https://opensea.io/collection/voxies on the indexer. Please help, thank you

**Comment by sanufriev** [comment]
@nfttrader hello, could you please point out a concrete example of issue with any item in this collection? I checked collection, and I don't see any obvious anomalies

**Comment by eduardstal** [comment]
After a private discussion with @nfttrader we both agreed that this issue should be closed as the issue was fixed.
