### ISSUE TITLE
Sell order not transferring funds or NFT

### ISSUE THREAD

**Issue by jsmellz** [rarible/protocol#147]
I’m getting an error where nfts aren’t being transferred for sell orders and funds aren't being transferred to nft creoter - is there any issue with sdk / api right now? - code here - https://github.com/Screensaver-world/RaribleProtocol-Interface/blob/be238a4e8bbdfaea84ce0aeff7afbdf9ad124f29/src/pages/mint.tsx#L62 

So after lazy minting sell order Is made using sdk (raribleSDK.order.sell)

Sell order request has this format:
  ```
    const request: SellRequest = {
        makeAssetType: {
          assetClass: 'ERC721',
          contract: toAddress(CONTRACT_ID),
          tokenId: toBigNumber(token.tokenId),
        },
        amount: 1,
        maker: toAddress(address),
        originFees: [],
        payouts: [],
        price: web3.utils.toWei(data.price.replace(',', '')).toString(),
        takeAssetType: { assetClass: data['price-currency'] },
      };
```

when matching order:

order/orders/${hash}/prepareTx - this endpoint is called with body provided below (maker is buyer’s address, amount is always 1)
```
{
    maker,
    amount,
    payouts: [],
    originFees: [],
  }
```

result is extracted and passed to web3.eth.sendTransaction(tx);

**Comment by evgenynacu** [comment]
@jsmellz is there a tx? Is it sent?
Or no transaction has occured?

**Comment by jsmellz** [comment]
@mladibejn

**Comment by mladibejn** [comment]
Everything works as expected! 

The problem was only a mistake, metamask doesn't show transaction on seller's side and I didn't notice changes in balance because small values were used. 
Sorry I haven't checked etherscan, completely forgot about it!  

Feel free to close it @jsmellz || @evgenynacu

**Comment by evgenynacu** [comment]
@mladibejn thanks!
Closing it
