### ISSUE TITLE
 sdk order.sell not working for ERC1155

### ISSUE THREAD

**Issue by aecorredor** [rarible/protocol#150]
I'm trying to create a sell order from my front-end client on an RFC1155 token I own and I'm getting the following error:

```
{
  "code": "INCORRECT_LAZY_ASSET",
  "message": "Invalid signatures for creators [0x28d431d565b97815473a4773634acbfc1f12421b] for lazy asset on make side",
  "status": 400
}
```

Here's the code:

```js
const orderBuilder = await raribleSdk.order.sell({
  makeAssetType: {
    assetClass: 'ERC1155',
    contract: toAddress(
      config.get('myown1155contractaddress')
    ),
    tokenId: toBigNumber(
      extractTokenIdFromItemId(nft.previewNft.itemId)
    ),
  },
  maker: toAddress(ownership.owner.ethAddress),
  amount: quantity,
  price: getValues('price'),
  payouts: [],
  originFees: [
    {
      account: toAddress(config.get('myownaddress')),
      value: 250,
    },
  ],
  takeAssetType: { assetClass: 'ETH' },
});
```

and here's the request I see in the browser:

```
{
  "maker": "0x28d431d565b97815473a4773634acbfc1f12421b",
  "make": {
    "assetType": {
      "@type": "ERC1155",
      "contract": "0x927b2ed99edd05a1fbef4de4e1775ada0901d4c2",
      "tokenId": "18467429459816144863947812166421793754398676185957064781363011930739185811472",
      "uri": "/ipfs/QmSsKPRpMwUHNT7fJDJQ3nRsBAJBNskeatbYhNtTKr9uL8",
      "creators": [
        {
          "account": "0x28d431d565b97815473a4773634acbfc1f12421b",
          "value": 10000
        }
      ],
      "royalties": [
        {
          "account": "0x28d431d565b97815473a4773634acbfc1f12421b",
          "value": 500
        },
        {
          "account": "0xee5f8c3e15b2d9280f060f01fc08c2f2f3b4476b",
          "value": 1000
        }
      ],
      "signatures": [
      "0x107899f9ff79bad2c9659c6154d661c5badf20daea4e6f5bcb820d5fe946674e47cb524e0f53842d1df04304ff65da14343a8cb2b5e2cc2b3f87c2f47d3face01c"
      ],
      "supply": "10",
      "assetClass": "ERC721_LAZY"
    },
    "value": "2"
  },
  "take": { "assetType": { "assetClass": "ETH" }, "value": "2" },
  "type": "RARIBLE_V2",
  "data": {
    "dataType": "RARIBLE_V2_DATA_V1",
    "payouts": [],
    "originFees": [
      { "account": "0x28d431d565b97815473a4773634acbfc1f12421b", "value": 250 }
    ]
  },
  "salt": "34945805662674558592829447995129376213206409534291223948514422231105297539999",
  "signature": "0x24bda6f87871cc6fbac173e60aa46b95847a42c1ac7097c5b59bb346289dd1a367272f444f15009d4d875570e154d51aabd1235ea44b3d635af46b20e87d6ee11b"
}
```

I'm 100% sure I own the NFT, so I'm not sure how the signature could be wrong. I set all this up by following the README on this repo and on the `protocol-example` repo. Am I sending wrong params when calling `order.sell`?

I do see `"assetClass": "ERC721_LAZY"` in the request body, which does seem completely wrong since I'm dealing with an 1155.

**Comment by aecorredor** [comment]
The bug is definitely that the SDK is setting `assetClass` to `ERC721_LAZY` even when `ERC1155` is specified. I dug around the source code but didn't find the place where the issue was at a glance.

**Comment by evgenynacu** [comment]
@aecorredor what sdk version you use?
I remember something about this bug. But I think we fixed it in the latest versions
Could you try to upgrade and see if it works ok now

**Comment by aecorredor** [comment]
I was on `0.5.1`, and I had upgraded about a month ago. I just upgraded to `0.9.9` and I'm getting different errors. Also, are the examples up to date in the repos? I find myself having to go back and forth to find the right examples for using the SDK's latest version.

**Comment by aecorredor** [comment]
Ok, I had to upgrade both `@rarible/web3-ethereum` and  `@rarible/protocol-ethereum-sdk` to their latest version (0.9.9). Now things work and everything seems to be direct now? No more needing to call `.run()`?

Also, I have a question about the pricing. The `price` is supposed to be in wei?

**Comment by aecorredor** [comment]
Everything is working after updating to the latest sdk version. Thanks for the help. I also confirmed that the price needs to be in wei.

**Comment by evgenynacu** [comment]
@aecorredor there is a possibility to set price in eth. Do you use typescript? If yes, you should see that there is one more field: priceDecimal. It's in ether. So it can be more convenient to use it

**Comment by aecorredor** [comment]
> @aecorredor there is a possibility to set price in eth. Do you use typescript? If yes, you should see that there is one more field: priceDecimal. It's in ether. So it can be more convenient to use it

I do use TypeScript. Thanks for the tip. It might be good to document this.
