### ISSUE TITLE
API - Reported Assets

### ISSUE THREAD

**Issue by bruck93** [rarible/protocol#152]
Hello,
is possible to add a property in the JSON, in which the metadata are included, in which is possible to see if an asset is reported/banned due to a fraudulent activities ?

Take a look at this Bored Ape, already blocked here:
https://rarible.com/token/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d:9564?tab=details

If you could add those infos here, in this call (and in the other in which you display the metadata) would be great:

https://ethereum-api.rarible.org/v0.1/nft/items/byOwner?owner=0xfcfb7c0954f5c82d1c81214560d540897ffd9aec&includeMeta=true

Thanks in advance.
Bruckzr

**Comment by eduardstal** [comment]
The Rarible.com API has a field in item-controller that can check for blacklisted items. 

See: https://rarible.com/marketplace/api/v4/items/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d:9564 

<img width="962" alt="Screenshot 2021-11-08 at 17 49 30" src="https://user-images.githubusercontent.com/39627934/140792663-f190c593-f56d-4624-b7fa-f93ca88b4b2e.png">

**Comment by bruck93** [comment]
Solved @eduardstal , thanks!
