### ISSUE TITLE
API - Reported Asset

### ISSUE THREAD

**Issue by bruck93** [rarible/protocol#160]
Hello,
as suggested by @eduardstal we've used this endpoint: **_https://rarible.com/marketplace/api/v4/items/_**

We found an issue on a couple of assets, for example this one:
https://rarible.com/marketplace/api/v4/items/0x0938E3F7AC6D7f674FeD551c93f363109bda3AF9:761

{"code":"UnknownError","message":"E11000 duplicate key error collection: rarible.item index: token_1_tokenId_1 dup key: { token: \"0x0938e3f7ac6d7f674fed551c93f363109bda3af9\", tokenId: \"761\" }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: rarible.item index: token_1_tokenId_1 dup key: { token: \"0x0938e3f7ac6d7f674fed551c93f363109bda3af9\", tokenId: \"761\" }"}

Could you please check?

Thanks,
Bruckzr

**Comment by bruck93** [comment]
The whole collection seems that have the same issue: https://opensea.io/collection/rtfkt-capsule-space-drip-1-2

**Comment by eduardstal** [comment]
I can replicate it as well. I've gotten in touch with Eugene & the marketplace team about this.

**Comment by evgenynacu** [comment]
There is a problem with upper-case chars
https://api-mainnet.rarible.com/marketplace/api/v4/items/0x0938e3f7ac6d7f674fed551c93f363109bda3af9:761

We will investigate this (lower case issue)
Meanwhile I close this
