### ISSUE TITLE
"ipfs pin add" through your protocol not actually pin anythings :)

### ISSUE THREAD

**Issue by holyknight113** [rarible/protocol#162]
Hello,

Just notice that using your protocol only "ipfs pin add" on your local IPFS node without actually pinning it on the entire IPFS nodes don't really know if it ever pin it on your local IPFS Node... 

It seems you use IPFS only for synchronizing and then the files are immediately deleted from Rarible’s IPFS node, and cached on Rarible’s CDN instead.

Are you working on it ?

Best regards

**Comment by evgenynacu** [comment]
@holyknight113 I don't get where you tried to pin IPFS files.
We don't provide any IPFS nodes on the protocol now
