### ISSUE TITLE
NFT Asset Detail - Info

### ISSUE THREAD

**Issue by bruck93** [rarible/protocol#165]
Hello,
we're using this endpoint, for example this one related to MAYC #27756:
https://ethereum-api.rarible.org/v0.1/nft/items/0x60e4d786628fea6478f785a6d7e704777c86a7c6:27756/meta

Yesterday when I've typed in the discord group, the PREVIEW section _image.preview_ were not filled yet, but now seems working fine:

`{"name":"MutantApeYachtClub #27756","attributes":[{"key":"Background","value":"M1 Aquamarine"},{"key":"Fur","value":"M1 Black"},{"key":"Mouth","value":"M1 Dumbfounded"},{"key":"Eyes","value":"M1 Robot"},{"key":"Clothes","value":"M1 Black Holes T"},{"key":"Hat","value":"M1 Bandana Blue"}],"image":{"url":{"ORIGINAL":"ipfs://ipfs/QmWqG4G6DaxD8Bi1Eeeu3JusBJ5XsVdTVT43hScZNHNbmF","BIG":"https://lh3.googleusercontent.com/69Qn4832Bw83jR7kfGbA7ixLlfrBYz2YJz6cEEJnAvCw8N8__YoKfEaiFHatFmVDwDimeVqldUWczjkYyxD4C6VnaIkHglQVU1Wu5Q","PREVIEW":"https://lh3.googleusercontent.com/69Qn4832Bw83jR7kfGbA7ixLlfrBYz2YJz6cEEJnAvCw8N8__YoKfEaiFHatFmVDwDimeVqldUWczjkYyxD4C6VnaIkHglQVU1Wu5Q=s250"},"meta":{"PREVIEW":{"type":"image/png","width":250,"height":250}}}}`

May I ask how this work and how much time is needed for recover that infos? Or if is better use an alternative?
Thanks!

**Comment by eduardstal** [comment]
Indexing an item varies in time usually because of network congestion, if all the data is not indexed yet 10-20 mins should do.
