### ISSUE TITLE
"Accept Bid" reverts on ERC1155 item

### ISSUE THREAD

**Issue by peak3d** [rarible/protocol#168]
When we try to accept the latest Bid (0.23 ETH) for this token:
https://rarible.com/token/0xd07dc4262bcdbf85190c01c996b4c06a461d2430:127893?tab=bids,
the execution of the TX is reverted (approval succeeds)

I simulated the TX in tenderly, but do not fully understand the reason why it reverts:

![image](https://user-images.githubusercontent.com/22704999/141990095-745dafd5-f863-4eb0-b192-11ad5d9a050f.png)

I can re-simulate / debug / provide more stack if required.

**Comment by eduardstal** [comment]
Hey, are you using the latest SDK version. We believe this was solved in the latest version.

**Comment by peak3d** [comment]
@eduardstal I use the UI (rarible.com), and picked the request from browser console (and fired in tenderly to get a debug trace)

**Comment by eduardstal** [comment]
In this case, since the issues you're encountering are related to using the Rarible.com marketplace. The place where you can get support from is https://discord.gg/rarible & https://rariblecom.zendesk.com/hc/en-us
