### ISSUE TITLE
Unable to Fill Bids in example repo

### ISSUE THREAD

**Issue by Jshanks21** [rarible/protocol#171]
@Jshanks21 
Could you share the code you trying to use?

Also, you can't make bids in ETH (only in WETH)
We should throw an error now if you try to do it (will add this error when you try to call SDK)

_Originally posted by @evgenynacu in https://github.com/rarible/example/issues/1#issuecomment-969900423_

I've been having difficulty filling bids on our app and tried using the example repo to see how the logic for filling bids works. However, the logic to fill bids in the example repo doesn't work either. The code for the example repo is here:

https://github.com/rarible/example

Behavior:

When I try to fill a bid, I get an error: transfer failed
https://rinkeby.etherscan.io/tx/0x3172f1c040a606b659a150abc36a638365b6468be748a14bcc974d1f9f02debe

For trying to fill the bid here: https://rinkeby.rarible.com/token/0x6ede7f3c26975aad32a475e1021d8f6f39c89d82:21578908932561758899859799426716046057317812514208370568897978054285555924994?tab=bids

Expected Behavior:

I'm able to accept the bid and receive Rinkeby ETH for the sale.

Steps to recreate:

1. Create a new lazy mint NFT
2. Connect with a new account and create a bid
3. Reconnect with the account that created the lazy NFT and fill the bid from the previous step

I believe the bids default to using ETH. The code for bidding specifically is in `src/order/bid.tsx` and looks like this:

```
import { IRaribleSdk } from "@rarible/sdk/build/domain"
import React from "react"
import { FormWithResult } from "../common/form-with-result"
import { PrepareForm } from "./prepare-form"
import { OrderForm } from "./form"

export function Bid({ sdk }: { sdk: IRaribleSdk }) {
	return (
		<FormWithResult
			renderForm={onSubmit => <PrepareForm onSubmit={onSubmit}/>}
			process={sdk.order.bid}
		>{prepareResponse => (
			<FormWithResult
				renderForm={onSubmit => <OrderForm onSubmit={onSubmit} response={prepareResponse}/>}
				process={prepareResponse.submit}
			>{orderId => <p>{orderId}</p>}</FormWithResult>
		)}</FormWithResult>
	)
}
```
Please keep in mind, I did not write this code, so I have no real insight on it other than looking at it and testing for accepting bids.

**Comment by eduardstal** [comment]
The example repo is not yet updated so it's broken. We will fix this sometime in the future. 

We've got someone working on a new app @kolberszymon that's also going to support bids so maybe you could work with that in the future.

**Comment by eduardstal** [comment]
This has now been fixed.
