### ISSUE TITLE
Royalties not being set getting invalid address error

### ISSUE THREAD

**Issue by ghardukan** [rarible/protocol#176]
When I try to set the royalties on rarible collection after claiming it I get the following Error. This behavior is same for both rinkerby testnet and mainnet of ETH can any one assist with the issue?
Error
invalid address (argument="address", value={"blockchain":"ETHEREUM","raw":"0xe9bc6cc5cb091078dc869772cb5e21b39eece460","origin":"0xe9bc6cc5cb091078dc869772cb5e21b39eece460","displayable":"0xe9bc6cc5cb091078dc869772cb5e21b39eece460"}, code=INVALID_ARGUMENT, version=address/5.5.0) (argument="account", value={"blockchain":"ETHEREUM","raw":"0xe9bc6cc5cb091078dc869772cb5e21b39eece460","origin":"0xe9bc6cc5cb091078dc869772cb5e21b39eece460","displayable":"0xe9bc6cc5cb091078dc869772cb5e21b39eece460"}, code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153). If the problem persist please Contact support

**Comment by eduardstal** [comment]
Hey there. From what I can see the issues you're encountering are related to using the Rarible.com marketplace. The place where you can get support from is https://discord.gg/rarible & https://rariblecom.zendesk.com/hc/en-us
