### ISSUE TITLE
ETA or Clear no:  Support for protocol only clients

### ISSUE THREAD

**Issue by bobwith2bees** [rarible/protocol#177]
Could we get a roadmap estimate when openapi based protocol clients for rarible will be stable or supported?   If the intention is to only support the SDK for the next 6+ months, then I suggest updating all the documents to remove the word "protocol" and replace it with "sdk" to avoid user confusion.

Support for protocol clients would include
* versioning of the API protocol
* written expectations of API support lifecycle (deprecation. end of support etc.)
* (bonus points) some unit tests that should fail if the protocol is changed.  Something we can watch in the repo for potential impacts to our production.

-- 
It is totally ok to be SDK focused and just get it work for now, but please be clear what you can support or not.  Repeated asking "Why are you not using the SDK?" doesn't help me make a business decision.  Thanks

**Comment by eduardstal** [comment]
Hey Bob, I think this would be a good topic to discuss on the call happening in 1h 15m in discord on the WG-VOICE channel. Do you think you could attend?
