### ISSUE TITLE
Deprecated docs

### ISSUE THREAD

**Issue by zakariamofaddel** [rarible/protocol#192]
Hi guys! I know things move very fast and I appreciate your work very much, I just wish the docs or the examples (https://github.com/rarible/protocol-example/) were up to date :/

I am trying to create a sell order following the example using this:
```
const resultOrder = await sdk.order.sell(request);

if (resultOrder) {
        setPurchaseOrderForm({ ...purchaseOrderForm, hash: resultOrder.thenStage() });
}
```
But the current resultOrder has no hash property, it has three methods (build, thenAction, thenStage) that I cannot find any docs about.

Is there any technical support to contact in these cases?

Thank you again for the awesome technologies your are building!

**Comment by evgenynacu** [comment]
@rarible/tech-writer-protocol-team pls check this issue

**Comment by evgenynacu** [comment]
@zakariamofaddel are you using latest sdk version? Didn't you miss await?
sdk.order.sell(request) should return Promise<Order>

so this should work fine (and it does in example project)
