### ISSUE TITLE
Two Indexer Issues

### ISSUE THREAD

**Issue by nfttrader** [rarible/protocol#203]
Hi, there are a few issues our users are having with the indexer. 
First one is that the Gutter Rats collection is not updating. For example, this owner
https://rarible.com/token/0xd7b397edad16ca8111ca4a3b832d0a5e3ae2438c:2487?tab=owners

Second, there is a user who got back his collection of stolen NFTs but on Rarible they are still flagged. Can you please unflag these assets as they are ok now? Thank you.
https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9985/
https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/2031/
https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9564/

**Comment by gawainb** [comment]
The indexer issue has been resolved. Recommended, to create a ticket with rarible.com to have the flagged NFTs whitelisted.
