### ISSUE TITLE
Metadata broken (protocol-ethereum-sdk)

### ISSUE THREAD

**Issue by hynra** [rarible/protocol#226]
Minting was successful, but the metadata seems broken in the response. I've captured requests and responses from the minting process:

Request
![eth-0](https://user-images.githubusercontent.com/3982650/148742764-180d80b7-02b1-4645-b3cf-a207ceb9531f.png)

```json
{
	"contract": "0xf6793da657495ffeff9ee6350824910abc21356c",
	"uri": "/bafyreia6bbopc72kps6d4jzuzwlvktxjqbwbqjlzemk656yel7bpnfq3t4/metadata.json",
	"royalties": [],
	"creators": [{
		"account": "0xdecadaa6af52409a0d2845467c99a5a459faddec",
		"value": 10000
	}],
	"tokenId": "100771864567088606639819364800134046827649680631603929184983121084958231232525",
	"@type": "ERC721",
	"signatures": ["0xa51af7fe222ebfe2a4f7484caeb4d78893bf80accc0e6ccf5dfc68d2f5e0dc5f4f25864ceaaeedaa1c395e7596718a8a94e1f926ee65729edb4b4d4f07ab23371b"]
}

```

Response:
![eth-1](https://user-images.githubusercontent.com/3982650/148742817-38e8793d-db25-470d-8449-080695b6ccc3.png)

```json
{
	"id": "0xf6793da657495ffeff9ee6350824910abc21356c:100771864567088606639819364800134046827649680631603929184983121084958231232525",
	"contract": "0xf6793da657495ffeff9ee6350824910abc21356c",
	"tokenId": "100771864567088606639819364800134046827649680631603929184983121084958231232525",
	"creators": [{
		"account": "0xdecadaa6af52409a0d2845467c99a5a459faddec",
		"value": 10000
	}],
	"supply": "1",
	"lazySupply": "1",
	"owners": ["0xdecadaa6af52409a0d2845467c99a5a459faddec"],
	"royalties": [],
	"date": "2022-01-10T06:58:41.495Z",
	"pending": [],
	"deleted": false,
	"meta": {
		"name": "Untitled",
		"attributes": []
	}
}
```

Seems like the metadata does not process properly at the endpoint, even though the uri passed into the parameter is correct and can be read as in the following evidence:

![eth-2](https://user-images.githubusercontent.com/3982650/148743571-c7e12732-453d-49f9-bdc9-f553dd139556.png)

```json
{
	"name": "Identity Card submission for Testing Out 7",
	"description": "Name: Hendra Permana\nDesc: Submission for Testing Out 7\nDate: 10/1/2022",
	"attributes": [{
		"trait_type": "powered by",
		"value": "https://markyour.id"
	}, {
		"trait_type": "curator",
		"value": "0xdecadaa6af52409a0d2845467c99a5a459faddec"
	}, {
		"trait_type": "created at",
		"value": "Mon, 10 Jan 2022 06:53:00 GMT"
	}, {
		"trait_type": "purpose",
		"value": "submission for Testing Out 7"
	}],
	"image": "ipfs://bafybeiavylk2f5kka5n23nwn4vzfjtt5keskpxwl6x7kjmedcoyags3ggi/1641797760851.jpg"
}
```

For the record, I use the latest Ethereum protocol SDK ( `"@rarible/protocol-ethereum-sdk": "^0.12.28"`).

![eth-3](https://user-images.githubusercontent.com/3982650/148743993-b896ba42-c657-4dc6-a4d2-4b0f08b0ffa0.png)

Did I miss something?

**Comment by eduardstal** [comment]
I believe your request URI is wrong. Should be: 

`/ipfs/bafyreia6bbopc72kps6d4jzuzwlvktxjqbwbqjlzemk656yel7bpnfq3t4/metadata.json`

instead of 

`/bafyreia6bbopc72kps6d4jzuzwlvktxjqbwbqjlzemk656yel7bpnfq3t4/metadata.json`

Could you let me know if this fixes it?

**Comment by hynra** [comment]
Actually, the uri I've passed to `uri` parameter in `MintRequest` is: `ipfs://bafyreia6bbopc72kps6d4jzuzwlvktxjqbwbqjlzemk656yel7bpnfq3t4/metadata.json`, but somehow SDK  forced the URI to `/bafyreia6bbopc72kps6d4jzuzwlvktxjqbwbqjlzemk656yel7bpnfq3t4/metadata.json` (without prefix), so maybe that is the problem.

I also tried changing the `ipfs://` prefix to `/ipfs/` as you suggested, but I got an error:

```
mint-eth.ts?6cb5:23 Error: uri must start with: ipfs:/
    at sanitizeUri (sanitize-uri.js?564d:7)
    at eval (mint-off-chain.js?e976:88)
    at step (tslib.es6.js?a65a:102)
    at Object.eval [as next] (tslib.es6.js?a65a:83)
    at fulfilled (tslib.es6.js?a65a:73)
```

![Screenshot 2022-01-10 185031](https://user-images.githubusercontent.com/3982650/148761595-a9083684-0f13-4f86-8fe8-568a9aaef4c1.png)

**Comment by hynra** [comment]
I had to add `/ipfs/` manually after `ipfs://` prefix to make this work, so the full `uri` that I should be put in the parameter is `ipfs://ipfs/bafyreia6bbopc72kps6d4jzuzwlvktxjqbwbqjlzemk656yel7bpnfq3t4/metadata.json`.  

That is the `uri` I got from my `ipfs` provider (without `/ipfs/`), so maybe I should make some adjustments before the `uri` is minted

Anyway, thank you for your help @eduardstal .
