### ISSUE TITLE
cancel_list duplicate bug when fetching order activities

### ISSUE THREAD

**Issue by martinAlt335** [rarible/protocol#248]
Hi, I found an interesting bug that duplicates a cancel_list order when fetching order activities.

I have not explored if this bug persists outside of this query; I've only tested on this specific query with the only change being on the size and types parameter. I noticed that there was a persistent duplication of objects that have the cancel_list type when there are multiple types set.

Here's a curl example of this bug which shows this duplication;

**Bugged request:**
`curl -XPOST -H "Content-type: application/json" -d '{
  "@type": "by_collection",
  "contract": "0xed5af388653567af2f388e6224dc7c4b3241c544",
  "types": [
"CANCEL_LIST", "LIST", "MATCH"
  ]
}' 'https://ethereum-api.rarible.org/v0.1/order/activities/search?continuation=1642781293000_61eada83fa963d40822ff05f&sort=EARLIEST_FIRST&size=2'`

The two objects returned are identical. This bug does not persist when the types parameter only has "CANCEL_LIST" set. I have not explored further possible combinations.

**Working request:**
`curl -XPOST -H "Content-type: application/json" -d '{
  "@type": "by_collection",
  "contract": "0xed5af388653567af2f388e6224dc7c4b3241c544",
  "types": [
"CANCEL_LIST"
  ]
}' 'https://ethereum-api.rarible.org/v0.1/order/activities/search?continuation=1642781293000_61eada83fa963d40822ff05f&sort=EARLIEST_FIRST&size=2'`

P.S: Appreciate the work on the Rarible API, it's a strong powerhouse tool that I hope will continually be maintained in the distant future. All the best to the team, great work!

**Comment by martinAlt335** [comment]
just realised this has been posted in protocol instead of ethereum-indexer. Opened the [issue there](https://github.com/rarible/ethereum-indexer/issues/220)

**Comment by eduardstal** [comment]
@martinAlt335 it should be opened here instead.

**Comment by martinAlt335** [comment]
> @martinAlt335 it should be opened here instead.

Ok, adding it back now, closing other.

**Comment by eduardstal** [comment]
We've tested this and found some weird behavior, will investigate further.

**Comment by eduardstal** [comment]
<details>

<summary>Filtering by type match - response contains `cancel_list` type (the weird behaviour) </summary>
{
    "continuation": "1642781309000_61eadabcfa963d40822ff6b0",
    "items": [
        {
            "@type": "cancel_list",
            "id": "61eada83fa963d40822ff061",
            "date": "2022-01-21T16:08:13Z",
            "source": "OPEN_SEA",
            "hash": "0x89ab525cad54853dd7abe07d2e75b0c097dd8ac529a81a95c28a589772eda460",
            "maker": "0xb21fd73a9b3682b8a9f31adcf49ffb32a04914b5",
            "make": {
                "assetClass": "ERC721",
                "contract": "0xed5af388653567af2f388e6224dc7c4b3241c544",
                "tokenId": "2708"
            },
            "take": {
                "assetClass": "ETH"
            },
            "transactionHash": "0x1c074080322a9355d5a9aa6688f64fd4918170d7a08ceb7aa13e33899fe16d7e",
            "blockHash": "0x274e8f322e5d9ca7303df9c4538d8675110ff3ca4fdf10fa2f9a93b165674b8c",
            "blockNumber": 14049896,
            "logIndex": 178
        },
        {
            "@type": "cancel_list",
            "id": "61eada83fa963d40822ff063",
            "date": "2022-01-21T16:08:13Z",
            "source": "OPEN_SEA",
            "hash": "0xbed328b8ec66c0e7d9c2749e64510c1d1ce68e125a03813ed2309a7155c01082",
            "maker": "0x3ee0abdbd1d4f8a99c0e4c2f786683bd8a2731ad",
            "make": {
                "assetClass": "ERC721",
                "contract": "0xed5af388653567af2f388e6224dc7c4b3241c544",
                "tokenId": "4802"
            },
            "take": {
                "assetClass": "ETH"
            },
            "transactionHash": "0x3a734d139351b86555929bd1dd14757f87dd57d8df30022c507317d10af86c84",
            "blockHash": "0x274e8f322e5d9ca7303df9c4538d8675110ff3ca4fdf10fa2f9a93b165674b8c",
            "blockNumber": 14049896,
            "logIndex": 196
        },
        {
            "@type": "match",
            "id": "61eada83fa963d40822ff06e",
            "date": "2022-01-21T16:08:13Z",
            "source": "OPEN_SEA",
            "left": {
                "maker": "0x7b59793ad075e4ce1e35181054759c080b8d965d",
                "hash": "0x8b6112864626a1daa9f878e6edddc4c733f87aa1ed0b06773e4d19be085a7c2f",
                "asset": {
                    "assetType": {
                        "assetClass": "ERC721",
                        "contract": "0xed5af388653567af2f388e6224dc7c4b3241c544",
                        "tokenId": "8952"
                    },
                    "value": "1",
                    "valueDecimal": 1
                },
                "type": "SELL"
            },
            "right": {
                "maker": "0xdd21500eba9c3a054161f3856c1c804953772176",
                "hash": "0xf1827e880c05693d56c3e18495fdc939102ecf8ef238ca6569ce4595ec904ec9",
                "asset": {
                    "assetType": {
                        "assetClass": "ETH"
                    },
                    "value": "23000000000000000000",
                    "valueDecimal": 23.000000000000000000
                },
                "type": "BID"
            },
            "price": 23.000000000000000000,
            "priceUsd": 64005.49859215108200000000000000000,
            "transactionHash": "0x6003ab69ee320b161edbd4f098124857254a6ce73fa343a8a1978d3b3fcbf26f",
            "blockHash": "0x274e8f322e5d9ca7303df9c4538d8675110ff3ca4fdf10fa2f9a93b165674b8c",
            "blockNumber": 14049896,
            "logIndex": 207,
            "type": "SELL"
        },
        {
            "@type": "cancel_list",
            "id": "61eadabcfa963d40822ff6a9",
            "date": "2022-01-21T16:08:29Z",
            "source": "OPEN_SEA",
            "hash": "0xc4a5e2030f7f29790d37b7c05fed09fb7bd452eb2de45cfe09cfa431a7807a5e",
            "maker": "0x45cf3e4edfcd1b135ab60f0a5d121846263fda88",
            "make": {
                "assetClass": "ERC721",
                "contract": "0xed5af388653567af2f388e6224dc7c4b3241c544",
                "tokenId": "6606"
            },
            "take": {
                "assetClass": "ETH"
            },
            "transactionHash": "0xd24d93d437124daa6f2639b902fc32a8f73504852c349c9e6ffed780a076217e",
            "blockHash": "0x8e9e917362517290e432fa49acd423a78d3c71e6bedcee8853a523768bd6c1fb",
            "blockNumber": 14049898,
            "logIndex": 207
        },
        {
            "@type": "match",
            "id": "61eadabcfa963d40822ff6b0",
            "date": "2022-01-21T16:08:29Z",
            "source": "OPEN_SEA",
            "left": {
                "maker": "0x8ffecb10b851f152fa97a92574c868be97a2e8e9",
                "hash": "0xb29087e4831dbd5a2127ff9437961fb9f03a6ab38416901ad5467b3d8eb45037",
                "asset": {
                    "assetType": {
                        "assetClass": "ERC721",
                        "contract": "0xed5af388653567af2f388e6224dc7c4b3241c544",
                        "tokenId": "4746"
                    },
                    "value": "1",
                    "valueDecimal": 1
                },
                "type": "SELL"
            },
            "right": {
                "maker": "0x0181ab16665123bde415211cceba0f8a975f2ffa",
                "hash": "0xc8bf2b1490ccdf0e7010284788b5ddd82ec3cfe4b31b5c782a85c7e684c0584f",
                "asset": {
                    "assetType": {
                        "assetClass": "ETH"
                    },
                    "value": "5000000000000000000",
                    "valueDecimal": 5.000000000000000000
                },
                "type": "BID"
            },
            "price": 5.000000000000000000,
            "priceUsd": 13914.23882438067000000000000000000,
            "transactionHash": "0x2c8577a2f0aafd5b8d7586a5a5b792a502b5babf9ee9f8149f68ba87927bbcc6",
            "blockHash": "0x8e9e917362517290e432fa49acd423a78d3c71e6bedcee8853a523768bd6c1fb",
            "blockNumber": 14049898,
            "logIndex": 532,
            "type": "SELL"
        }
    ]
}
</details>

When filtering by type `CANCEL_LIST` or `LIST` no duplicates are found. When filtering using both `CANCEL_LIST` and `LIST` duplicates are found which could be a cause of `CANCEL_LIST` being of type `LIST`. 
Not sure if this should be considered a bug or it's just a weird way of displaying the response.

**Comment by eduardstal** [comment]
We've added this to our backlog and will most likely start working on it next week.

**Comment by eduardstal** [comment]
Fixed now.
