### ISSUE TITLE
circular references on v0.1/collections/all endpoint

### ISSUE THREAD

**Issue by ianapiron** [rarible/protocol#249]
Hey 👋

As the title says, following the `continuation` param returned by the `v0.1/collections/all` endpoint, have ended up 2/2 times so far on an endless loop because of circular references.

The last of the times, it occurred using the following continuation params:
* endpoint: `https://api.rarible.org/v0.1/collections/all?continuation=0x06076993de0d56433315e4d80c0232dd57275c51`
* continuation returned: `KT18c8n9jbpDRZStQRvZUC1GPBEDEcVgwGFC`
=>
* endpoint: `https://api.rarible.org/v0.1/collections/all?continuation=KT18c8n9jbpDRZStQRvZUC1GPBEDEcVgwGFC`
* continuation returned: `0x06076993de0d56433315e4d80c0232dd57275c51`

Let me know if I can help in any way.

**Comment by eduardstal** [comment]
Seems the data you provided initially is slightly inaccurate, still, it seems that it loops. Here's what I found below. 

Endpoint: https://api.rarible.org/v0.1/collections/all?continuation=0x06076993de0d56433315e4d80c0232dd57275c51

Continuation: 0x05fee3b8e939acbb4e8073d784e3ec0977509770

Endpoint: https://api.rarible.org/v0.1/collections/all?continuation=0x05fee3b8e939acbb4e8073d784e3ec0977509770

Continuation: KT18aqCooZxt5VS4vZM6rsJfhf8aDWkkbTT2

Endpoint: https://api.rarible.org/v0.1/collections/all?continuation=KT18aqCooZxt5VS4vZM6rsJfhf8aDWkkbTT2

Continuation: 0x05fee3b8e939acbb4e8073d784e3ec0977509770

**Comment by ianapiron** [comment]
Hey @eduardstal, no idea why you say they're inaccurate tbh as they were returned and logged on my side by the time of this ticket's creation. Obviously the references were changing all the time (I just provided one example of IDs in here) but the pattern of the loop was that it was happening after getting a "weird" continuation ID like `KT18c8n9jbpDRZStQRvZUC1GPBEDEcVgwGFC` in my example and `KT18aqCooZxt5VS4vZM6rsJfhf8aDWkkbTT2` from your example. After that, it would most probably loop.

I hope the above helps and I remain at your disposal for any further testing you might need from my side.

**Comment by eduardstal** [comment]
Seems to be fixed now. Closing this.
