### ISSUE TITLE
SDK Conversion error

### ISSUE THREAD

**Issue by henriqueantonio** [rarible/protocol#262]
Hey!

Some API responses that return the ID have changed but the SDK still expecting the old ones.

From: `id: "BLOCKCHAIN:CONTRACT"`
To: `id: { type: "BLOCKCHAIN", value: "CONTRACT"}`

![Captura de Tela 2022-02-14 às 10 32 29](https://user-images.githubusercontent.com/39568828/153878084-e68ee765-36b4-41aa-a522-e58afc474d11.png)

![Captura de Tela 2022-02-14 às 10 29 31](https://user-images.githubusercontent.com/39568828/153878146-82e2acb3-7c20-49b3-92da-a2f72b977854.png)

![Captura de Tela 2022-02-14 às 10 32 38](https://user-images.githubusercontent.com/39568828/153877357-3ea8079c-4a1d-4998-b535-63d06bacc8c6.png)

The image above is one example, it expects to receive a string, but received an object.

These conversions happen pretty much in the entire SDK, invalidating the creation of collections, mint of assets and so on.

**Comment by eduardstal** [comment]
This is a work in progress and should be fixed soon. I will close the issue once I have confirmation it's fixed.

**Comment by ex1st0r** [comment]
[henriqueantonio](https://github.com/henriqueantonio) Could you give me example of API request with such id?

**Comment by henriqueantonio** [comment]
> [henriqueantonio](https://github.com/henriqueantonio) Could you give me example of API request with such id?

The problem have already been fixed!
