### ISSUE TITLE
Refresh metadata for OG:Crystals project

### ISSUE THREAD

**Issue by dandaka** [rarible/protocol#263]
**Now**

Metadata for collection OG:Crystals is outdated

https://rarible.com/ogcrystals/items

Token https://rarible.com/token/0x368ad4a7a7f49b8fa8f34476be0fc4d04ce622f5:2986?tab=details
Meta https://api.ogcrystals.com/api/v1/crystals/meta/2986.json
Actual image https://api.ogcrystals.com/api/v1/crystals/images/original/2986/7.jpg

**Expected**

Updated metadata for all tokens in this collection

**Comment by eduardstal** [comment]
Finished refreshing metadata for all 10301 tokens in the collection. Let me know if you find any that still have outdated metadata.
