### ISSUE TITLE
Ethereum API - searchNftAllCollections and getNftAllItems issues

### ISSUE THREAD

**Issue by ejlmorais** [rarible/protocol#267]
Hello,

So I'm trying to get all the **NFT Collections** looping the Ethereum API, using the retrieved continuation token in each response on the following request, but I was only able to get 3 pages of results, (2 continuation tokens) even changing the size in the request.
I tried both 10 and 1000 values on the size, and the number of collections that I'm getting is 10 + 10 + 9 and 1000 + 1000 + 999
```
https://ethereum-api.rarible.org/v0.1/nft/collections/all?size=10
https://ethereum-api.rarible.org/v0.1/nft/collections/all?size=1000
```

For the **NFT Items** I was also doing the continuation token loop request, but in this case when I use a bigger size I get a time-out, and using a lower size, I am only able to get a limited number of page results (+-40).
```
https://ethereum-api.rarible.org/v0.1/nft/items/all?size=1000
```

Can you take a look please? 
Thanks

**Comment by eduardstal** [comment]
Managed to replicate this as well.

**Comment by hedgedon** [comment]
I have tested this pagination issue today and it seems to have been fixed.

**Comment by eduardstal** [comment]
Can confirm the same on my end, closing this issue.
