### ISSUE TITLE
400 bad requests https://api-dev.rarible.com/protocol/v0.1/ethereum/nft/mints

### ISSUE THREAD

**Issue by tungnguyentp** [rarible/protocol#269]
i have param 
{"contract":"0xB0EA149212Eb707a1E5FC1D2d3fD318a8d94cf05","uri":"/ipfs/Qmcbs7ZQKdCdp1wkv1uvwxLAT7VfjgD78B6cGGA1XpF5P9","tokenURI":"/ipfs/Qmcbs7ZQKdCdp1wkv1uvwxLAT7VfjgD78B6cGGA1XpF5P9","royalties":[{"account":"0x77382ca68A21951B14eEb1e0712B2740aa269A89","value":1000}],"creators":[{"account":"0x77382ca68A21951B14eEb1e0712B2740aa269A89","value":10000}],"tokenId":"53924480583773606537317486921640320769422156755955051799039655670327483039746","@type":"ERC721","signatures":["0x29a0aea4dedbba0baced550ba732727bb300baf85c2ebe71050441cbda0656c1d111a07a856b220234a5492456fc85149d8921beb345817cbdd5adeb70564874a54b491b"]}

Someone please tell me how to signatures a correct way in swift language

**Comment by bobwith2bees** [comment]
There is a swift port of WalletConnect https://docs.walletconnect.com/quick-start/wallets/swift
WalletConnect can accept a [signedTypeData request ](https://docs.walletconnect.com/client-api#sign-typed-data-eth_signtypeddata)and relay that to a 3rd party crypto wallet to sign.

**Comment by eduardstal** [comment]
Closing due to the issue owner not responding, please reopen if needed.
