### ISSUE TITLE
It's possible to make bid with ETH, not WETH?

### ISSUE THREAD

**Issue by alexey708** [rarible/protocol#279]
When I have using example, I was try to make bid with ETH currency (changed asset type in example code), but sdk returns error: 
`Make asset type should be ERC-20, received=ETH`

It's protocol limitation or something else?

**Comment by disenotov** [comment]
Hello!
Indeed, bids can't be made in ETH due to the fact that ETH should be sent along with transaction, and transaction is sent only when orders are matched. Not when bid is places. 
Hope that helps.
