### ISSUE TITLE
error while migrating out of gas

### ISSUE THREAD

**Issue by Rasoooll** [rarible/protocol#293]
. Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.

the contracts wont deploy on ganache-cli
I have  changed the gas in truffle-config but it didn't help.
I have tried this command "ganache-cli --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000"
but this time it ran of gas on deployProxy().

**Comment by eduardstal** [comment]
Closing due to the issue owner not responding.
