### ISSUE TITLE
Polygon contract owner incorrect on rarible.com

### ISSUE THREAD

**Issue by bobwith2bees** [rarible/protocol#301]
My Polygon collection has the wrong owner on rarible.com.   I used the same method as I did for my Ethereum contract that does not have this issue.   It is possible I incorrectly deployed the contract, because I was unable to find documentation on how actually deploy a contract on Polygon.  (See related https://github.com/rarible/protocol/discussions/300 )

* https://rarible.com/collection/polygon/0x91A408bEDC9Fb4e1305456b184515BF0C7c81249/items
* https://polygonscan.com/address/0x91A408bEDC9Fb4e1305456b184515BF0C7c81249#events (shows my wallet 0x10125A128bdE30d5f208d05fe2B88Ad25eBb7e6a in the transfer)

**Comment by Devjohn68** [comment]
A support ticket has been opened for you. Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.org/)

**Comment by bobwith2bees** [comment]
@eduardstal  - The Devjohn68 response above looks like phishing attempt.  Please remove it so no one is mislead in thinking this it is legitimate response.
