### ISSUE TITLE
ropsten.rarible.com not registering new collection ids created with sdk.nft.createCollection

### ISSUE THREAD

**Issue by vicwtang** [rarible/protocol#307]
when SDK_ENV='dev' - sdk.nft.createCollection on dev - I get a txhash and a created contract - ie the call succeeds and the collection is created.
However ropsten.rarible.com does not register it - you do not see it in the collections for the wallet it was created on. Calls to the minting api fails due to the contract not existing.
However the same code on staging(rinkeby) succeeds and mints fine.

**Comment by eduardstal** [comment]
Could you provide more details about minting failing due to the contract not existing? 

Your code should be fine. Usually ropsten is less reliable, so rinkeby should be the go-to for testing.

**Comment by vicwtang** [comment]
Hi Eduard,
I havent used dev in a few days. Just tested again and the issue is still
there:
1st call to create a collection:
        const response = await connection.sdk.nft.createCollection(params);
params

   1.
            1. params:
               1. asset:
                  1. arguments:
                     1. baseURI: "ipfs:/"
                     2. contractURI: "
                     https://api-ropsten.rarible.com/contractMetadata/{address}
                     "
                     3. isUserToken: true
                     4. name: "test rop5"
                     5. operators: []
                     6. symbol: "rop5"
                     7. [[Prototype]]: Object
                  2. assetType: "ERC721"
                  3. [[Prototype]]: Object
               2. blockchain: "ETHEREUM"

response

   1. address: "ETHEREUM:0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d"
   2. tx: BlockchainEthereumTransaction
      1. blockchain: "ETHEREUM"
      2. network: "ropsten"
      3. transaction: Web3Transaction
         1. data:
         "0x27050d1f00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e098483428b547befb79543023c71e313d2ec1b710a9bad781efea23b8cf22753a00000000000000000000000000000000000000000000000000000000000000097465737420726f703500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004726f7035000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006697066733a2f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003a68747470733a2f2f6170692d726f707374656e2e72617269626c652e636f6d2f636f6e74726163744d657461646174612f7b616464726573737d0000000000000000000000000000000000000000000000000000000000000000000000000000"
         2. from: "0xc85fe33585784212e77269ce95d54556726a2e4c"
         3. hash:
         "0x9754c48bb440380cda5dd3b543e6068c0eeea07cd047cfe01e4b7ab8a1b08426"
         4. nonce: 6
         5. receipt: Promise
            1. [[Prototype]]: Promise
            2. [[PromiseState]]: "fulfilled"
            3. [[PromiseResult]]: Object
               1. blockHash:
               "0x50f394d2d6104f4dc03f11c8d52a3dce99e9f2a1b99f167377949a3206ecb8e6"
               2. blockNumber: 12154803
               3. contractAddress: null
               4. cumulativeGasUsed: 787992
               5. effectiveGasPrice: 2500774955
               6. events:
                  1. 0: {address:
                  '0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d', blockHash:

'0x50f394d2d6104f4dc03f11c8d52a3dce99e9f2a1b99f167377949a3206ecb8e6'
                  , blockNumber: 12154803, logIndex: 2, removed: false, …}
                  2. 1: {address:
                  '0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d', blockHash:

'0x50f394d2d6104f4dc03f11c8d52a3dce99e9f2a1b99f167377949a3206ecb8e6'
                  , blockNumber: 12154803, logIndex: 3, removed: false, …}
                  3. 2: {address:
                  '0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d', blockHash:

'0x50f394d2d6104f4dc03f11c8d52a3dce99e9f2a1b99f167377949a3206ecb8e6'
                  , blockNumber: 12154803, logIndex: 4, removed: false, …}
                  4. Create721RaribleUserProxy:
                     1. address:
                     "0x939d0308CE4274C287E7305D381B336B77dBfcd3"
                     2. blockHash:

"0x50f394d2d6104f4dc03f11c8d52a3dce99e9f2a1b99f167377949a3206ecb8e6"
                     3. blockNumber: 12154803
                     4. event: "Create721RaribleUserProxy"
                     5. id: "log_986b7555"
                     6. logIndex: 6
                     7. raw: {data:

'0x0000000000000000000000007f15e7ee489f5f6dc29fd993fb88233616e6ae3d'
                     , topics: Array(1)}
                     8. removed: false
                     9. returnValues: Result
                        1. 0: "0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d"
                        2. proxy:
                        "0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d"
                        3. [[Prototype]]: Object
                     10. signature:

"0x4768a3e06654c109507892e111851106a07f51f57cc0cfc3374a141e03c3f08f"
                     11. transactionHash:

"0x9754c48bb440380cda5dd3b543e6068c0eeea07cd047cfe01e4b7ab8a1b08426"
                     12. transactionIndex: 3
                     13. [[Prototype]]: Object
                  5. OwnershipTransferred: Array(2)
                     1. 0:
                        1. address:
                        "0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d"
                        2. blockHash:

"0x50f394d2d6104f4dc03f11c8d52a3dce99e9f2a1b99f167377949a3206ecb8e6"
                        3. blockNumber: 12154803
                        4. event: "OwnershipTransferred"
                        5. id: "log_8b604dfc"
                        6. logIndex: 1
                        7. raw: {data: '0x', topics: Array(3)}
                        8. removed: false
                        9. returnValues: Result {0:
                        '0x0000000000000000000000000000000000000000', 1:
                        '0x939d0308CE4274C287E7305D381B336B77dBfcd3',
                        previousOwner:
                        '0x0000000000000000000000000000000000000000',
                        newOwner:
                        '0x939d0308CE4274C287E7305D381B336B77dBfcd3'}
                        10. signature:

"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0"
                        11. transactionHash:

"0x9754c48bb440380cda5dd3b543e6068c0eeea07cd047cfe01e4b7ab8a1b08426"
                        12. transactionIndex: 3
                        13. [[Prototype]]: Object
                     2. 1:
                        1. address:
                        "0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d"
                        2. blockHash:

"0x50f394d2d6104f4dc03f11c8d52a3dce99e9f2a1b99f167377949a3206ecb8e6"
                        3. blockNumber: 12154803
                        4. event: "OwnershipTransferred"
                        5. id: "log_04ee2e8b"
                        6. logIndex: 5
                        7. raw: {data: '0x', topics: Array(3)}
                        8. removed: false
                        9. returnValues: Result {0:
                        '0x939d0308CE4274C287E7305D381B336B77dBfcd3', 1:
                        '0xC85Fe33585784212e77269CE95D54556726a2E4C',
                        previousOwner:
                        '0x939d0308CE4274C287E7305D381B336B77dBfcd3',
                        newOwner:
                        '0xC85Fe33585784212e77269CE95D54556726a2E4C'}
                        10. signature:

"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0"
                        11. transactionHash:

"0x9754c48bb440380cda5dd3b543e6068c0eeea07cd047cfe01e4b7ab8a1b08426"
                        12. transactionIndex: 3
                        13. [[Prototype]]: Object
                     3. length: 2
                     4. [[Prototype]]: Array(0)
                  6. [[Prototype]]: Object
               7. from: "0xc85fe33585784212e77269ce95d54556726a2e4c"
               8. gasUsed: 685186
               9. logsBloom:
               "0x00000000000000000000000000000000000800000002000000800000000000000000000000000008000000000000000000000000000000000800000000000000000040000000000000000000000000000001002000000000000000104000000000000000020000000000203000000800000000400000000400800000000001400000000000000000000000400080000000000000000000000000000000000000000000000000000800000000000080000000000080000000040000000000000000000000000000000000000010000000000000000000000000000000000020040000008000000000000000800000001000000000000000000000000001000000"
               10. status: true
               11. to: "0x939d0308ce4274c287e7305d381b336b77dbfcd3"
               12. transactionHash:
               "0x9754c48bb440380cda5dd3b543e6068c0eeea07cd047cfe01e4b7ab8a1b08426"
               13. transactionIndex: 3
               14. type: "0x2"
               15. [[Prototype]]: Object
            6. to: "0x939d0308ce4274c287e7305d381b336b77dbfcd3"
         7.


   1.
      1.

2nd call to Mint with collection = address from previous call: address:
"ETHEREUM:0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d"
    const collection = await sdk.apis.collection.getCollectionById({
        collection: collectionId,
    });
results in following fetch:
GET
https://api-dev.rarible.org/v0.1/collections/ETHEREUM%3A0x7f15e7ee489F5F6Dc29fd993fB88233616e6Ae3d
which gets a 404

   1. value: {code: 'NOT_FOUND', message: 'Collection with id
   0x7f15e7ee489f5f6dc29fd993fb88233616e6ae3d not found'}
   2.

**Comment by evgenynacu** [comment]
Closing the issue as stale
Feel free to reopen this if needed
