### ISSUE TITLE
Ethereum specific API: Unreliable attributes output

### ISSUE THREAD

**Issue by vaultec81** [rarible/protocol#308]
The attributes property inside the NFT metadata at random can be empty or filled with proper data. One request might yield a proper output for the array, another might be completely missing. Below is the url of the NFT I am pulling with screenshots of the output changing between requests.

Steps to reproduce:
1. Request the following URL
2. Note the output being an empty array or filled with valid attributes,
3. Reload the page
4. The output should change after a few reloads

```
https://ethereum-api.rarible.org/v0.1/nft/items/0x049aba7510f45ba5b64ea9e658e342f904db358d:72395029413885780036203903487367895700679395196806361478441957442796494991391
```
![Screenshot 2022-03-31 100136](https://user-images.githubusercontent.com/47548474/161111834-84f86530-53f5-45e7-8828-77bf68120b3c.png)
![Screenshot 2022-03-31 100203](https://user-images.githubusercontent.com/47548474/161111841-4f842ecc-8440-4f14-b5f2-beed547ec4d2.png)

**Comment by eduardstal** [comment]
Managed to reproduce as well. It seems the Multichain API is also affected by this bug.

**Comment by eduardstal** [comment]
We've identified the issue and fixed it. The fix will be deployed around tomorrow morning EU time.

**Comment by eduardstal** [comment]
Fixed, closing.
