### ISSUE TITLE
Rarible Indexer - Issue

### ISSUE THREAD

**Issue by bruck93** [rarible/protocol#309]
Dear Rarible Protocol Team,
we've noticed, as NFTTrader.io, that since some weeks some props were completely removed from the Rarible Indexer.

This is the main one that is missing right now.

Calling this endpoint (Example: https://ethereum-api.rarible.org/v0.1/nft/items/0xdbd4264248e2f814838702e0cb3015ac3a7157a1:1/meta )

The property **image.url.BIG** is completely disappeared. Could you please check it?
Thanks.

**Comment by eduardstal** [comment]
Hey @bruck93, 

I believe this is related to: https://github.com/rarible/protocol/issues/308

I've managed to replicate the same behavior from the issue listed above.

**Comment by eduardstal** [comment]
Hey @bruck93. We have fixed this on the Multichain API. 
https://api.rarible.org/v0.1/items/ETHEREUM:0xdbd4264248e2f814838702e0cb3015ac3a7157a1:1

`ethereum-api` is still affected and you should migrate away from it.

**Comment by eduardstal** [comment]
Closing this now.
