### ISSUE TITLE
getSellOrdersByMaker not respecting status filter

### ISSUE THREAD

**Issue by vaultec81** [rarible/protocol#311]
Greetings, I am trying to get a list of sellOrders filtered by status. It appears the API does not respect the requested status and returns a list of sales that may or may not be in the ACTIVE status as seen in the below URL.

```https://api.rarible.org/v0.1/orders/sell/byMaker?maker=TEZOS:tz1ZZw3FSj14D27K37FMVkRiHWgS9doQ5L8m&status=ACTIVE```

Data returned from the above url at time of writing this 
![image](https://user-images.githubusercontent.com/47548474/161314322-827e40b8-4def-46de-81ad-c57509993e1f.png)

Let me know if I am missing something here

**Comment by eduardstal** [comment]
This problem only affects the Tezos API. Other blockchains are filtering correctly. 

We have started working on a fix for this.
