### ISSUE TITLE
image.url.BIG is unstable. Some requests seem to have this property, some requests don't. 

### ISSUE THREAD

**Issue by nfttrader-dev** [rarible/protocol#319]
Dear Rarible Team,

I would like to request an escalation on this issue as we have our users running into the same problem for many of their NFTs and collections not loading in their wallets when using our platform. 

There is a problem with this endpoint (Example: https://ethereum-api.rarible.org/v0.1/nft/items/0xdbd4264248e2f814838702e0cb3015ac3a7157a1:1/meta )

The property image.url.BIG is completely disappeared. Please look into this asap. Thank you.

**Comment by eduardstal** [comment]
Hey there. 

An issue for this bug has already been opened: https://github.com/rarible/protocol/issues/309
I will escalate the priority of this issue. 

Also, you should migrate away from ethereum-api and start using the multichain api. You can find the API doc here: https://multichain-api.rarible.org

**Comment by eduardstal** [comment]
I'll point this out before closing, this issue is fixed on the Multichain API.

https://api.rarible.org/v0.1/items/ETHEREUM:0xdbd4264248e2f814838702e0cb3015ac3a7157a1:1

`ethereum-api` is still not stable and you should migrate away from it.
