### ISSUE TITLE
Manifold being reported to AWS as a bot scraper (we are not)

### ISSUE THREAD

**Issue by wwhchung** [rarible/protocol#320]
Rarible has reported Manifold for calling the metadata refresh api too often, and reported us as a bot.

eg
/marketplace/api/v4/items/0x06911466341299D79E9E1368A016C73d009691cc%3A1284/meta/refresh

We need to do this because of dynamic NFTs, collection reveals, and because our Studio product allows people to update NFT metadata.  We need to call meta/refresh in order to keep Rarible in sync.  Can you please retract this report?

**Comment by eduardstal** [comment]
Adding more context here: 

```
Hello,

We've received a report(s) that your AWS resource(s)

AWS ID: 743799374440    Region: us-east-1    NAT Gateway Id: nat-012d568f989007854

has been implicated in activity which resembles web-crawling; the reporter of the activity has indicated that the activity is unwelcome, disruptive, or excessive. Operating a webcrawler at an excessive or disruptive rate is forbidden in the AWS Acceptable Use Policy (https://aws.amazon.com/aup/). We've included the original report below for your review.
```

**Comment by eduardstal** [comment]
Hey there @wwhchung, 

I believe this was fixed on our end. Could you confirm this?

**Comment by wwhchung** [comment]
yup, thanks!
