### ISSUE TITLE
Missing ownership data of an NFT / Broken pagination 

### ISSUE THREAD

**Issue by vaultec81** [rarible/protocol#321]
We've found that the ownership API does not return a complete list of owners of an NFT. 

Steps to repro
1) Go to https://api.rarible.org/v0.1/ownerships/byItem?itemId=TEZOS:KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton:602052&size=50
2) Note a non empty ownerships array with plenty of data
3) Go to https://api.rarible.org/v0.1/ownerships/byItem?itemId=TEZOS:KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton:602052&size=50&continuation=1640458860000_KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton:602052:tz2J2L8AtCnKaCeeGD7Zq6fEMRRDCohR4Sre
4) Note a completely empty ownership array 

We can only get a limited number of owners, yet the total amount is well above the 50 that was requested above.

From step 1 
![image](https://user-images.githubusercontent.com/47548474/162269420-0867afde-d0b4-4916-bb02-8b408f61e520.png)

From step 3
![image](https://user-images.githubusercontent.com/47548474/162269481-1002755d-3eca-4276-9cbc-4e34a2dfbd98.png)

**Comment by eduardstal** [comment]
Another concern would be that `"total": 0,` can be found in both responses, regardless of the amount of ownerships returned. 

We're on it!

**Comment by vaultec81** [comment]
@eduardstal Any updates on this?

**Comment by yakischik** [comment]
Should works now
https://api.rarible.org/v0.1/ownerships/byItem?itemId=TEZOS:KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton:602052&size=50&continuation=1640458860000_KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton:602052:tz1iZ9yHJzgvC4oBvHsrNmtL8GHPqtwqshAi
