### ISSUE TITLE
Type 'ContractAddress' is not assignable to type 'CollectionId'

### ISSUE THREAD

**Issue by EgoInc** [rarible/protocol#329]
### Discussed in https://github.com/rarible/protocol/discussions/328

<div type='discussions-op-text'>

<sup>Originally posted by **EgoInc** April 11, 2022</sup>
Hello. I'm trying to run some mint function, for example from here
<https://github.com/rarible/protocol/blob/4dd47059a31ff6bde1241f14469de6e07138d28b/docs/reference/mint-and-sell.md>

But I always get an error
```
createNft.ts:12:9 - error TS2322: Type 'ContractAddress' is not assignable to type 'CollectionId'.  
  Property '"__IS_COLLECTION_ID__"' is missing in type 'String & { __IS_CONTRACT_ADDRESS__: true; }' but required in type '{ __IS_COLLECTION_ID__: true; }'.

12         collectionId: toContractAddress(contractAddress),
```

Here is function:
```ts
const mintAction = await sdk.nft.mintAndSell({
	collectionId: toContractAddress("TEZOS:KT18pVpRXKPY2c4U2yFEGSH3ZnhB2kL8kwXS"),
})
```

</div>

**Comment by eduardstal** [comment]
You should use `toCollectionId` instead of `toContractAddress`.

**Comment by mazinden** [comment]
@eduardstal fixed

**Comment by eduardstal** [comment]
Closing this, please reopen if you encounter any other issues.
