### ISSUE TITLE
Missing Tezos NFTs from pixelpotus contract

### ISSUE THREAD

**Issue by vaultec81** [rarible/protocol#330]
I've found that the union API is missing the following NFTs/contracts on Tezos. These NFTs appear fine on objkt but are not returned on

https://api.rarible.org/v0.1/items/TEZOS:KT1WGDVRnff4rmGzJUbdCRAJBmYt12BrPzdD:2045
https://api.rarible.org/v0.1/items/byOwner?owner=TEZOS:tz2P6gHkZSfpdiYmJG7LVZncqaHb7x4Hu8oc&size=50 <-- Returns some NFTs but not all.

Link the the collection on objk https://objkt.com/collection/pixelpotus
Profile that owns the above NFT: https://objkt.com/profile/tz2P6gHkZSfpdiYmJG7LVZncqaHb7x4Hu8oc/owned
contract address: KT1WGDVRnff4rmGzJUbdCRAJBmYt12BrPzdD

There are multiple NFTs from the pixelpotus collection that are missing. Any idea what could be happening here?

**Comment by eduardstal** [comment]
Hey @vaultec81 

There seems to have been an indexing issue with this contract. We'll re-launch indexing. The ETA on this should be around 1-2 days.

**Comment by eduardstal** [comment]
Closing this as it was fixed.
