### ISSUE TITLE
@rarible/sdk/src dependency does not exist

### ISSUE THREAD

**Issue by my-Gem** [rarible/protocol#334]
@rarible/sdk/src dependency does not exist, how to solve this problem?

**Comment by my-Gem** [comment]
@rarible/sdk-wallet/src dependency does not exist

**Comment by my-Gem** [comment]
please help me

**Comment by my-Gem** [comment]
please help me

**Comment by eduardstal** [comment]
Hey there, could you point out what specific issues you are encountering? I need some more details in order to properly understand your problem.
