### ISSUE TITLE
getItemsByOwner supply is 1 but not on direct query

### ISSUE THREAD

**Issue by vaultec81** [rarible/protocol#336]
Hey, I've found an issue using the union API where the returned supply value is 1, however in reality it is much more than 1.

Observe the following queries

https://api.rarible.org/v0.1/items/byOwner?owner=TEZOS:tz1ZZw3FSj14D27K37FMVkRiHWgS9doQ5L8m <-- Returns a list of NFTs. For the purpose of this demonstration I will be using the first returned NFT (TEZOS:KT1CzVSa18hndYupV9NcXy3Qj7p8YFDZKVQv:10)
Notice the supply is only a single edition.
Now access that same NFT directly:
https://api.rarible.org/v0.1/items/TEZOS:KT1CzVSa18hndYupV9NcXy3Qj7p8YFDZKVQv:10

Notice the supply is 831 at the time of writing this. Quite different than the original value of 1.

**Comment by eduardstal** [comment]
Hey @vaultec81 

We're working on this. I've also managed to replicate the bug (832 at the time of writing)

Will follow up with updates

**Comment by eduardstal** [comment]
This is fixed. Closing.
