### ISSUE TITLE
api-staging.rarible.org/v0.1/items mintedAt field timestamp is incorrect/changing 

### ISSUE THREAD

**Issue by bobwith2bees** [rarible/protocol#340]
Priority: Low, but it does impact my monitoring/unit testing since mintedAt timestamp is later than the lastUpdatedAt timestamp.

https://multichain.redoc.ly/v0.1#operation/getItemById

https://api-staging.rarible.org/v0.1/items/ETHEREUM:0x6ede7f3c26975aad32a475e1021d8f6f39c89d82:51853873187524799243313032258623492611584136611923237689466576623960428904598

https://api-staging.rarible.org/v0.1/items/ETHEREUM:0x6ede7f3c26975aad32a475e1021d8f6f39c89d82:51853873187524799243313032258623492611584136611923237689466576623960428904788

The mintedAt field appears to be the current time.  Just reload the page in the browser and the mintedAt date changes.

**Comment by oanhcuongdo** [comment]
https://api-staging.rarible.org/v0.1 not works

**Comment by evgenynacu** [comment]
This was fixed some time ago (mintedAt)
So closing the issue
