### ISSUE TITLE
Smart Contract Addresses

### ISSUE THREAD

**Issue by EgoInc** [rarible/protocol#342]
Hello. I want to start my interaction with Rarible Development Environment in Tezos. So I'm trying to mint my NFT on development Tezos  - Hangzhounet, go to docs https://docs.rarible.org/reference/contract-addresses/ and see that in Development Section in Tezos there is a link "NFT: https://ithacanet.tzkt.io/KT1ANmrMfq6SfPe2b59JGVu2CDacoaoL6hW8"
But it's link to Ithacanet, not Hangzhounet

But you wrote here https://docs.rarible.org/api-reference/ that development environment is Hangzhou
![image](https://user-images.githubusercontent.com/56895607/163801003-b036ab6a-fb70-4de3-869e-2626c7573d0a.png)

So, where should I take Hangzhounet Tezos Smart Contract Address, because using Ithacanet I get an error: Request rejected
{"status":404,"value":{"code":"NOT_FOUND","message":"KT1ANmrMfq6SfPe2b59JGVu2CDacoaoL6hW8"}}

**Comment by eduardstal** [comment]
Hey there, we are using Ithacanet at the moment, we've recently switched from Hangzhounet.

I've fixed the documentation here: https://github.com/rarible/protocol/blob/main/docs/api-reference.md
