### ISSUE TITLE
Tokens not updating in a timely manner, even after sell order completed

### ISSUE THREAD

**Issue by vicwtang** [rarible/protocol#348]
I did a drop of 3300 ethereum lazy minted tokens, updated all with a sell price and received an orderId for each.
The tokens subsequently appear in the https://rarible.com/items/sale page. However, even after being minted for several days, the majority of these NFTs (ON PRODUCTION) are still appearing as "Content not available yet - refresh metadata".
What is required to get these items updated with the correct content? Should it not be immediately indexed if it is set for sale?
Please contact me directly for the collection/tokenid for reference.
Thanks

**Comment by vicwtang** [comment]
Hi guys, any update?
The items have valid sellOrderIds but no metadata...
There doesnt seem to be any rhyme or reason. here's 2 - one that worked, one that didn't, minted seconds apart.
"mintedAt":"2022-05-18T23:55:54.782Z"

One that worked:
https://api.rarible.org/v0.1/items/ETHEREUM:0x6dc6f1ebd33ad874a596908b11618e6229828510:113277356295846663305716423985495022567090845171550585720498478269451112287338?

One that didnt:
https://api.rarible.org/v0.1/items/ETHEREUM:0x6dc6f1ebd33ad874a596908b11618e6229828510:113277356295846663305716423985495022567090845171550585720498478269451112287337?

Thanks

**Comment by bobwith2bees** [comment]
I see similar issues in production. I am not aware of a programmatic way to check metadata loading status or initiate a reload on behalf of users using the SDK (I have asked.) 

On earlier dev calls the “content  it available workaround” was supposed to go away with all the indexer work for polygon, then solana.  Eager to see a written update.

On a positive rote the api uptime has improved.

**Comment by evgenynacu** [comment]
Closing the issue as it's rather old
After the issue was created we implemented many improvements regarding indexing speed and consistency. So this should be fixed

Let me know if you need any help and feel free to reopen the issue
