### ISSUE TITLE
https://api.rarible.org/v0.1/items/byOwner for Tezos is throwing ReadTimeoutException

### ISSUE THREAD

**Issue by vicwtang** [rarible/protocol#355]
Request URL: https://api.rarible.org/v0.1/items/byOwner?owner=TEZOS:tzwallet&size=25&includeMeta=true
throws error: {"code":"UNKNOWN","message":"nested exception is io.netty.handler.timeout.ReadTimeoutException"}

I've been reducing the size down to 25 and its still failing. Been doing this the past 4hrs at least.
I do have a large collection with approx 1000nfts in tezos - not sure if that's a factor.

**Comment by vicwtang** [comment]
now occasionally responding, but contents are incomplete - missing image and title

TEZOS nft object returns:
chainId: 1048577
collectionId: "TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b"
docRoot: undefined
image: undefined
itemId: "TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b:1091"
lazy: "0"
title: "Unnamed item"
tokenId: "1091"

Polygon NFT object returns:
chainId: 137
collectionId: "POLYGON:0x64f0788b9ead7429bacd9cd74b9ee45821419cc3"
docRoot: "QmZg6NeTtiBnis9xGiHruo7Ycsk7eeDrmup7MnKZ39woWE"
image: "https://ipfs.infura.io/ipfs/QmZg6NeTtiBnis9xGiHruo7Ycsk7eeDrmup7MnKZ39woWE/preview/Matilda%20%2372.png"
itemId: "POLYGON:0x64f0788b9ead7429bacd9cd74b9ee45821419cc3:7"
lazy: "0"
title: "Matilda #72"
tokenId: "7"

**Comment by eduardstal** [comment]
Hey there @vicwtang. We're currently working on migrating our backend. We can only start fixing this bug once we've migrated which will take 2-3 weeks.

**Comment by vicwtang** [comment]
Are there any alternative methods of retrieving the tezos collection for an
address?

**Comment by eduardstal** [comment]
I'm afraid that until we will migrate to the new backend, there are no alternatives. 

Let's keep this issue open, and I will send future updates about this situation here.

**Comment by evgenynacu** [comment]
Hi
Sorry for late reply!
We are discontinuing Tezos support https://discord.com/channels/1020069477490118748/1093554014840434708/1179413887959961671
