### ISSUE TITLE
Unable to import a Polygon collection - is this not supported

### ISSUE THREAD

**Issue by vicwtang** [rarible/protocol#356]
Rarible.com is able to display a 3rd polygon contract and show its contents, BUT when I go to import the collection, I get the error: We haven't found any collection related to your wallet. Check your connected wallet address or type another collection address

The wallet connected is POLYGON with the contract creator address.

Is only mainnet contracts importable at this time? When might polygon contracts be supported?

Thanks!

**Comment by FankDev** [comment]
@vicwtang Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

**Comment by eduardstal** [comment]
Removed @FankDev's reply as it was phishing attempt

**Comment by eduardstal** [comment]
After discussing this issue on Discord, it seems the collection we've been investigating for this GitHub issue does not support Ownable, therefore it won't be possible to see the owner of the collection. 

As a word of advice for devs of the future; you should use the Ownable pattern when deploying a contract. 
It should have the owner field & emit events (usually, the open zeppelin version does this) 

If Ownable is implemented, rarible.com should automatically see the current owner.
