### ISSUE TITLE
Issues refreshing collection

### ISSUE THREAD

**Issue by joehquak** [rarible/protocol#359]
Hi all!
We've got a collection that appears to not want to refresh on your site as the metadata for most items are empty for some reason.

https://rarible.com/collection/0x54e0395cfb4f39bef66dbcd5bd93cca4e9273d56/

Any help would be greatly appreciated

Many thanks!

**Comment by eduardstal** [comment]
Hi, we'll be looking into this. 
Most likely we will have to re-index the entire collection, I'll be sending updates here on how this process goes.

**Comment by janinewhite** [comment]
My Hydro Whales Mining Club NFTs are not refreshing their metadata when requested.  They are showing no information or the pre-reveal image. https://rarible.com/collection/0xba72b008d53d3e65f6641e1d63376be2f9c1ad05/items

**Comment by eduardstal** [comment]
@joehquak 

Please create your own github issue for this problem :) 

Thanks.

**Comment by joehquak** [comment]
> Hello @joehquak,
> 
> This should be fixed now, please check on your end and close the issue if everything looks in order.

Works perfectly! Thank you very much @eduardstal, really appreciate your help 😁
