### ISSUE TITLE
Link to following API references not working.

### ISSUE THREAD

**Issue by canedy** [rarible/protocol#360]
Base URL in the following location.

https://flow-api.rarible.com/v0.1/doc
http://flow-api-dev.rarible.com/v0.1/doc

read me file

https://github.com/rarible/flow-protocol-api

**Comment by eduardstal** [comment]
Hey there @canedy, 

You should be using our Multichain API. 

API Documentation: https://multichain-api.rarible.org 

Points to the following endpoints: 

- Mainnet: https://api.rarible.org/v0.1/
- Staging: https://api-staging.rarible.org/v0.1/
- Development: https://dev-api.rarible.org/v0.1/

Additionally, you should be taking a look at our documentation: https://docs.rarible.org

**Comment by eduardstal** [comment]
Closing this.
