### ISSUE TITLE
Why doesn't my Ethereum node have any peers ?

### ISSUE THREAD

**Issue by sekarvetrivel** [rarible/protocol#361]
Hi, I'm working on Ethereum indexer, try to connect mainnet using openethereum by rarible. it's connected to mainnet, listening command  also returns true but it can't find any peers. I've already tried the syncing command that also return false.but My bandwidth is good.
![Screenshot from 2022-05-30 10-54-28](https://user-images.githubusercontent.com/105904147/171000359-4980ead6-d7ea-4f2c-952e-39d5c4e29c52.png)
![Screenshot from 2022-05-30 18-05-16](https://user-images.githubusercontent.com/105904147/171000372-945e4643-2cc2-4e6d-829f-5d592d864104.png)
![Screenshot from 2022-05-30 18-05-21](https://user-images.githubusercontent.com/105904147/171000375-2e42f201-555b-493d-8de3-ce83f004ba59.png)
![Screenshot from 2022-05-30 18-05-26](https://user-images.githubusercontent.com/105904147/171000379-989a106b-a320-4ec6-82a7-5744425e9e2d.png)

**Comment by evgenynacu** [comment]
Hi @sekarvetrivel 
Sorry for late reply

We can't help with ethereum node. Probably, it's better to reach responsible team for it
