### ISSUE TITLE
Update @openzeppelin/contracts-upgradeable version

### ISSUE THREAD

**Issue by vicpon** [rarible/protocol#375]
Would it be possible to update the version of `@openzeppelin/contracts-upgradeable` used? I am using the latest version of the openzeppelin lib in one of my projects but can't use the rarible contracts because the versions are different.

This is the error I get in my contract when compiling:
```
Error HH404: File @openzeppelin/contracts-upgradeable/introspection/ERC165Upgradeable.sol, imported from @rarible/royalties-upgradeable/contracts/RoyaltiesV2Upgradeable.sol, not found.
```

The location of `ERC165Upgradeable.sol` has changed.

**Comment by disenotov** [comment]
Hi! sorry we can't update the @openzeppelin/contracts-upgradeable verson, because all our contracts use 0.7.6 compiler

**Comment by vicpon** [comment]
That was the point of the PR I opened, to update the contracts and the compiler being used. I've already done the work and an using the updated contracts in production. I bet you didn't even look at the PR...
