### ISSUE TITLE
Blockchains parameter filter does not work

### ISSUE THREAD

**Issue by ipatovanton** [rarible/protocol#401]
https://api.rarible.org/v0.1/items/byCreator?creator=ETHEREUM:0x03ee832367e29a5cd001f65093283eabb5382b62&blockchains=ETHEREUM

It gives out both ethereum and polygon

**Comment by evgenynacu** [comment]
@ipatovanton sorry for long reply
Are you still experiencing this?

I don't see this 
Let me know if you need help here?

**Comment by evgenynacu** [comment]
Closing this issue as stale
Feel free to reopen if needed
