### ISSUE TITLE
[Feedback] Rarible Protocol API Reference - /api-reference/

### ISSUE THREAD

**Issue by NitishBeejawat** [rarible/protocol#412]
Auction doesn`t work at your end.
API and documentation is not updated.
No proper communication is available to solve the issue.

  const ethCurrency: EthErc20AssetType = {
    "@type": "ERC20",
    contract: toContractAddress(
      "ETHEREUM:0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
    ),
  };

  const price: number = Number(bid);
  const amount: number = 1;

  const orderRequest: PrepareOrderRequest = {
    itemId: toItemId(tokenUnionAddress),
  };

  const bidResponse = await sdk?.order.bid(orderRequest);

  const response = await bidResponse?.submit({
    amount,
    price,
    currency: ethCurrency,
  });

Can anyone let me know what I can use for goerli testnet and mumbai testnet since I am getting "ETHEREUM:undefined" issue.

Earlier I was working with RINKEBY TESTNET so I have used above addres but now I have switched to GOERLI testnet so what address can I use.

**Comment by evgenynacu** [comment]
Thanks
Auctions are on hold now. We didn't yet release them. We will make sure this is clearly indicated in docs
