### ISSUE TITLE
Error occured Server error (403). Message from server: Unknown error

### ISSUE THREAD

**Issue by ibadullaev-inc4** [rarible/protocol#416]
contract address = 0xcf0af5ce0744ce2ec1c9e3eb747f829b64c2d36d
contract owner address = 0x4FEDB2a5f72AD6CD40048E0b9bee4AB5dd8FE14d

I deployed simple ERC-1155 implementation from openzeppelin on Mumbai network. 
Also I mint NFT via that contract and show them on https://testnet.rarible.com under My NFTs
But when I try to create collection ( "Import an Existing")  under Collections tab and put on my contract address, I faced the error:

![image](https://github.com/rarible/protocol/assets/101882172/08c605f7-0713-4514-b9b4-47ee3a9b6bc4)

Need I implement something special on my smartContract for possibility import it as new collection ?

**Comment by ibadullaev-inc4** [comment]
May be I need to implement proxies ? 

This is from your docs: 
**User-owned contracts use beacon proxies, and these contracts can be updated by Rarible DAO. Rarible common contracts can be upgraded too.**

**Comment by ibadullaev-inc4** [comment]
Any ideas ?

**Comment by ibadullaev-inc4** [comment]
Any ideas ?

**Comment by ibadullaev-inc4** [comment]
Up

**Comment by evgenynacu** [comment]
@ibadullaev-inc4 sorry for long reply
Do you need help here?

**Comment by evgenynacu** [comment]
Closing as stale
feel free to reopen if needed
