### ISSUE TITLE
Can I use Rarible protocol for new EVM blockchain?

### ISSUE THREAD

**Issue by JOY** [rarible/protocol#422]
Hi,

We have an EVM-based blockchain using Avalanche Subnet. I'd like to ask whether we can use the Rarible protocol to build our own NFT marketplace which supports our blockchain?

**Comment by evgenynacu** [comment]
Hi @JOY 
Sorry for long reply

Yes, it's possible
There are 2 alternatives:
1. You can deploy everything on your own
2. Work with us to spin up indexer for the chain and setup infra

Pls reach to me directly so I can pass this information to responsible people

**Comment by JOY** [comment]
@evgenynacu Sure. My email is anh@doslabs.io and my Telegram is @AnhLe

**Comment by evgenynacu** [comment]
I sent this information to BD team. Closing the ticket meanwhile
