### ISSUE TITLE
Deploy on Fuse network EVM sidechain

### ISSUE THREAD

**Issue by bertux** [rarible/protocol#7]
Hello, I am interested in deploying the Rarible Protocol on Fuse network EVM sidechain
I've already added support of Fuse network to Snapshot governance dApp and the Simple NFT example of Scaffold-eth which I've deployed on Fuse at https://fuse-nft.surge.sh
I have started by reading https://docs.rarible.org/ where I've discovered https://docs.rarible.org/starter-app to practice first on Ropsten testnet.
Then I will try to deploy locally as explained at https://github.com/rarible/protocol-contracts and will try to make starter-app work locally.

**Comment by fileflume** [comment]
This would be a great addition to Fuse and the Rarible DAO. 

Gooddollar.org (a top 5 dApp for users and txs) runs on Fuse.io, and this would open the door to their users (many in developing countries), and allow the use of NFTs for many projects - food banks, financial bonds, loans, games etc. 

Would be a great integration to have.

**Comment by evgenynacu** [comment]
We will look into all EVM compatible chains once we finish union service. (That's a service to combine blockchains together)
First EVM compatible chain will be polygon, then others will be connected too.

@bertux @fileflume
