### ISSUE TITLE
Upgradeable contracts == centralized?

### ISSUE THREAD

**Issue by jsmellz** [rarible/protocol#95]
Upgradeable contracts are a point of centralized power in the rarible protocol. Obviously, having a dao mitigates risks associated but most actual contract owners are priced out of voting - maybe there should be templates available (even in factory) where upgrades are controlled by contract owners? 🔥😘😊🎉🙇‍♂️

**Comment by mattreallycodes** [comment]
That seems like it would conflict with the DAO itself and almost go around it. This is intentional and shouldn't be changed, no?

**Comment by jsmellz** [comment]
that is possible
