### ISSUE TITLE
Date is not displayed on nft page

### ISSUE THREAD

**Issue by evgenynacu** [rarible/protocol#97]
### Discussed in https://github.com/rarible/protocol-issues/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **denGitHub** August 23, 2021</sup>
Trait date not displayed on the NFT page.

https://rinkeby.rarible.com/token/0x20d34e12657b2317be1ef1384d9d54cef087dcae:26?tab=details

**Active since** is empty.

This is how the trait is set on ipfs in metadata.json file

`{"display_type":"date","trait_type":"Active Since","value":1607385600}`

Though it works fine on opensea.

https://testnets.opensea.io/assets/0x20d34e12657b2317be1ef1384d9d54cef087dcae/26

**Active Since  Tuesday, December 8th, 2020**

Could you please help to figure out how the date can be displayed  on rarible as well?</div>

**Comment by evgenynacu** [comment]
Will be fixed soon

**Comment by mystdeim** [comment]
Fixed. If it occurs again we need to reset meta via api request. Later we improve date display
